### ISSUE TITLE
Exception when generating javadoc

### ISSUE THREAD

**Issue by testn** [TSergey/intellij-javadocs#46]
Got this error occasionally in Intellij 15

```
Attempt to modify PSI for non-committed Document!
java.lang.IllegalStateException: Attempt to modify PSI for non-committed Document!
    at com.intellij.pom.core.impl.PomModelImpl.b(PomModelImpl.java:323)
    at com.intellij.pom.core.impl.PomModelImpl.runTransaction(PomModelImpl.java:145)
    at com.intellij.psi.impl.source.tree.ChangeUtil.prepareAndRunChangeAction(ChangeUtil.java:166)
    at com.intellij.psi.impl.source.tree.CompositeElement.a(CompositeElement.java:941)
    at com.intellij.psi.impl.source.tree.CompositeElement.removeRange(CompositeElement.java:693)
    at com.intellij.psi.impl.source.codeStyle.CodeEditUtil.removeChildren(CodeEditUtil.java:172)
    at com.intellij.psi.impl.source.codeStyle.CodeEditUtil.removeChild(CodeEditUtil.java:62)
    at com.intellij.psi.impl.source.tree.CompositeElement.deleteChildInternal(CompositeElement.java:548)
    at com.intellij.psi.impl.source.tree.java.MethodElement.deleteChildInternal(MethodElement.java:79)
    at com.intellij.psi.impl.source.tree.LazyParseablePsiElement.delete(LazyParseablePsiElement.java:219)
    at com.github.setial.intellijjavadocs.operation.impl.JavaDocWriterImpl.deleteJavaDoc(JavaDocWriterImpl.java:175)
    at com.github.setial.intellijjavadocs.operation.impl.JavaDocWriterImpl.replaceJavaDoc(JavaDocWriterImpl.java:184)
    at com.github.setial.intellijjavadocs.operation.impl.JavaDocWriterImpl.access$000(JavaDocWriterImpl.java:31)
    at com.github.setial.intellijjavadocs.operation.impl.JavaDocWriterImpl$WriteJavaDocActionImpl.run(JavaDocWriterImpl.java:123)
    at com.intellij.openapi.application.RunResult.run(RunResult.java:35)
    at com.intellij.openapi.command.WriteCommandAction$2$1.run(WriteCommandAction.java:114)
    at com.intellij.openapi.application.impl.ApplicationImpl.runWriteAction(ApplicationImpl.java:1002)
    at com.intellij.openapi.command.WriteCommandAction$2.run(WriteCommandAction.java:111)
    at com.intellij.openapi.command.impl.CoreCommandProcessor.executeCommand(CoreCommandProcessor.java:124)
    at com.intellij.openapi.command.impl.CoreCommandProcessor.executeCommand(CoreCommandProcessor.java:99)
    at com.intellij.openapi.command.WriteCommandAction.performWriteCommandAction(WriteCommandAction.java:108)
    at com.intellij.openapi.command.WriteCommandAction.execute(WriteCommandAction.java:80)
    at com.github.setial.intellijjavadocs.operation.impl.JavaDocWriterImpl.write(JavaDocWriterImpl.java:66)
    at com.github.setial.intellijjavadocs.action.JavaDocGenerateAction.processElement(JavaDocGenerateAction.java:119)
    at com.github.setial.intellijjavadocs.action.JavaDocsGenerateAction.processFile(JavaDocsGenerateAction.java:102)
    at com.github.setial.intellijjavadocs.action.JavaDocsGenerateAction.actionPerformed(JavaDocsGenerateAction.java:65)
    at com.intellij.openapi.actionSystem.ex.ActionUtil.performActionDumbAware(ActionUtil.java:182)
    at com.intellij.openapi.actionSystem.impl.ActionMenuItem$ActionTransmitter$1.run(ActionMenuItem.java:311)
    at com.intellij.openapi.wm.impl.FocusManagerImpl.runOnOwnContext(FocusManagerImpl.java:958)
    at com.intellij.openapi.wm.impl.IdeFocusManagerImpl.runOnOwnContext(IdeFocusManagerImpl.java:124)
    at com.intellij.openapi.actionSystem.impl.ActionMenuItem$ActionTransmitter.actionPerformed(ActionMenuItem.java:281)
    at javax.swing.AbstractButton.fireActionPerformed(AbstractButton.java:2022)
    at com.intellij.openapi.actionSystem.impl.ActionMenuItem.fireActionPerformed(ActionMenuItem.java:109)
    at javax.swing.AbstractButton$Handler.actionPerformed(AbstractButton.java:2346)
    at javax.swing.DefaultButtonModel.fireActionPerformed(DefaultButtonModel.java:402)
    at javax.swing.JToggleButton$ToggleButtonModel.setPressed(JToggleButton.java:308)
    at javax.swing.AbstractButton.doClick(AbstractButton.java:376)
    at com.apple.laf.ScreenMenuItemCheckbox.itemStateChanged(ScreenMenuItemCheckbox.java:193)
    at java.awt.CheckboxMenuItem.processItemEvent(CheckboxMenuItem.java:389)
    at java.awt.CheckboxMenuItem.processEvent(CheckboxMenuItem.java:357)
    at java.awt.MenuComponent.dispatchEventImpl(MenuComponent.java:351)
    at java.awt.MenuComponent.dispatchEvent(MenuComponent.java:339)
    at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:754)
    at java.awt.EventQueue.access$500(EventQueue.java:97)
    at java.awt.EventQueue$3.run(EventQueue.java:702)
    at java.awt.EventQueue$3.run(EventQueue.java:696)
    at java.security.AccessController.doPrivileged(Native Method)
    at java.security.ProtectionDomain$1.doIntersectionPrivilege(ProtectionDomain.java:75)
    at java.security.ProtectionDomain$1.doIntersectionPrivilege(ProtectionDomain.java:86)
    at java.awt.EventQueue$4.run(EventQueue.java:724)
    at java.awt.EventQueue$4.run(EventQueue.java:722)
    at java.security.AccessController.doPrivileged(Native Method)
    at java.security.ProtectionDomain$1.doIntersectionPrivilege(ProtectionDomain.java:75)
    at java.awt.EventQueue.dispatchEvent(EventQueue.java:721)
    at com.intellij.ide.IdeEventQueue.f(IdeEventQueue.java:861)
    at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:649)
    at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:380)
    at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
    at java.awt.EventDispatchThread.null(Unknown Source)
    at java.awt.EventDispatchThread.null(Unknown Source)
    at java.awt.EventDispatchThread.null(Unknown Source)
    at java.awt.EventDispatchThread.null(Unknown Source)
    at java.awt.EventDispatchThread.null(Unknown Source)
```

**Comment by TSergey** [comment]
Have you got a 3.1.0 plugin version or do you work on previous version?

**Comment by testn** [comment]
3.1.0.. it only happens a couple times so far.
