### ISSUE TITLE
NPE: While Creating JavaDoc for all Elements

### ISSUE THREAD

**Issue by manivelpvn** [TSergey/intellij-javadocs#89]
2020-03-26 22:52:47,640 [ 212612]  ERROR - eration.impl.JavaDocWriterImpl - IntelliJ IDEA 2019.3.4  Build #IC-193.6911.18 
2020-03-26 22:52:47,640 [ 212612]  ERROR - eration.impl.JavaDocWriterImpl - JDK: 11.0.6; VM: OpenJDK 64-Bit Server VM; Vendor: JetBrains s.r.o 
2020-03-26 22:52:47,640 [ 212612]  ERROR - eration.impl.JavaDocWriterImpl - OS: Mac OS X 
2020-03-26 22:52:47,641 [ 212613]  ERROR - eration.impl.JavaDocWriterImpl - Plugin to blame: JavaDoc version: 4.0.1 
2020-03-26 22:52:47,641 [ 212613]  ERROR - eration.impl.JavaDocWriterImpl - Last Action: com.github.setial.intellijjavadocs.action.JavaDocsGenerateActionOnProject 
2020-03-26 22:52:48,733 [ 213705]  ERROR - eration.impl.JavaDocWriterImpl - null 
java.lang.NullPointerException
	at com.github.setial.intellijjavadocs.operation.impl.JavaDocWriterImpl.addJavaDoc(JavaDocWriterImpl.java:157)
	at com.github.setial.intellijjavadocs.operation.impl.JavaDocWriterImpl.access$100(JavaDocWriterImpl.java:33)
	at com.github.setial.intellijjavadocs.operation.impl.JavaDocWriterImpl$WriteJavaDocActionImpl.run(JavaDocWriterImpl.java:108)
	at com.intellij.openapi.command.WriteCommandAction$BuilderImpl$1.run(WriteCommandAction.java:110)
	at com.intellij.openapi.application.RunResult.run(RunResult.java:35)
	at com.intellij.openapi.command.WriteCommandAction.lambda$null$1(WriteCommandAction.java:251)
	at com.intellij.openapi.application.impl.ApplicationImpl.runWriteAction(ApplicationImpl.java:885)
	at com.intellij.openapi.command.WriteCommandAction.lambda$performWriteCommandAction$2(WriteCommandAction.java:250)
	at com.intellij.openapi.command.WriteCommandAction.lambda$doExecuteCommand$4(WriteCommandAction.java:308)
	at com.intellij.openapi.command.impl.CoreCommandProcessor.executeCommand(CoreCommandProcessor.java:220)
	at com.intellij.openapi.command.impl.CoreCommandProcessor.executeCommand(CoreCommandProcessor.java:188)
	at com.intellij.openapi.command.WriteCommandAction.doExecuteCommand(WriteCommandAction.java:310)
	at com.intellij.openapi.command.WriteCommandAction.performWriteCommandAction(WriteCommandAction.java:249)
	at com.intellij.openapi.command.WriteCommandAction.execute(WriteCommandAction.java:230)
	at com.intellij.openapi.command.WriteCommandAction$BuilderImpl.run(WriteCommandAction.java:112)
	at com.github.setial.intellijjavadocs.operation.impl.JavaDocWriterImpl.write(JavaDocWriterImpl.java:51)
	at com.github.setial.intellijjavadocs.action.JavaDocGenerateAction.processElement(JavaDocGenerateAction.java:150)
	at com.github.setial.intellijjavadocs.action.JavaDocsGenerateAction.processFile(JavaDocsGenerateAction.java:97)
	at com.github.setial.intellijjavadocs.action.JavaDocsGenerateAction.processFiles(JavaDocsGenerateAction.java:77)
	at com.github.setial.intellijjavadocs.action.JavaDocsGenerateAction.processFiles(JavaDocsGenerateAction.java:74)
	at com.github.setial.intellijjavadocs.action.JavaDocsGenerateAction.processFiles(JavaDocsGenerateAction.java:74)
	at com.github.setial.intellijjavadocs.action.JavaDocsGenerateAction.processFiles(JavaDocsGenerateAction.java:74)
	at com.github.setial.intellijjavadocs.action.JavaDocsGenerateAction.processFiles(JavaDocsGenerateAction.java:74)
	at com.github.setial.intellijjavadocs.action.JavaDocsGenerateAction.processFiles(JavaDocsGenerateAction.java:74)
	at com.github.setial.intellijjavadocs.action.JavaDocsGenerateAction.processFiles(JavaDocsGenerateAction.java:74)
	at com.github.setial.intellijjavadocs.action.JavaDocsGenerateAction.processFiles(JavaDocsGenerateAction.java:74)
	at com.github.setial.intellijjavadocs.action.JavaDocsGenerateAction.processFiles(JavaDocsGenerateAction.java:74)
	at com.github.setial.intellijjavadocs.action.JavaDocsGenerateAction.processFiles(JavaDocsGenerateAction.java:74)
	at com.github.setial.intellijjavadocs.action.JavaDocsGenerateAction.actionPerformed(JavaDocsGenerateAction.java:62)
	at com.intellij.openapi.actionSystem.ex.ActionUtil$1.run(ActionUtil.java:298)
	at com.intellij.openapi.application.TransactionGuardImpl.runSyncTransaction(TransactionGuardImpl.java:83)
	at com.intellij.openapi.application.TransactionGuardImpl.submitTransactionAndWait(TransactionGuardImpl.java:149)
	at com.intellij.openapi.actionSystem.ex.ActionUtil.performActionDumbAware(ActionUtil.java:313)
	at com.intellij.openapi.actionSystem.impl.ActionMenuItem$ActionTransmitter.lambda$actionPerformed$0(ActionMenuItem.java:294)
	at com.intellij.openapi.wm.impl.FocusManagerImpl.runOnOwnContext(FocusManagerImpl.java:263)
	at com.intellij.openapi.wm.impl.IdeFocusManagerImpl.runOnOwnContext(IdeFocusManagerImpl.java:77)
	at com.intellij.openapi.actionSystem.impl.ActionMenuItem$ActionTransmitter.actionPerformed(ActionMenuItem.java:284)
	at java.desktop/javax.swing.AbstractButton.fireActionPerformed(AbstractButton.java:1967)
	at com.intellij.openapi.actionSystem.impl.ActionMenuItem.lambda$fireActionPerformed$0(ActionMenuItem.java:112)
	at com.intellij.openapi.application.TransactionGuardImpl.runSyncTransaction(TransactionGuardImpl.java:83)
	at com.intellij.openapi.application.TransactionGuardImpl.lambda$submitTransaction$1(TransactionGuardImpl.java:107)
	at com.intellij.openapi.application.TransactionGuardImpl.submitTransaction(TransactionGuardImpl.java:116)
	at com.intellij.openapi.application.TransactionGuard.submitTransaction(TransactionGuard.java:121)
	at com.intellij.openapi.actionSystem.impl.ActionMenuItem.fireActionPerformed(ActionMenuItem.java:112)
	at com.intellij.ui.plaf.beg.BegMenuItemUI.doClick(BegMenuItemUI.java:517)
	at com.intellij.ui.plaf.beg.BegMenuItemUI.access$300(BegMenuItemUI.java:36)
	at com.intellij.ui.plaf.beg.BegMenuItemUI$MyMouseInputHandler.mouseReleased(BegMenuItemUI.java:539)
	at java.desktop/java.awt.Component.processMouseEvent(Component.java:6651)
	at java.desktop/javax.swing.JComponent.processMouseEvent(JComponent.java:3342)
	at java.desktop/java.awt.Component.processEvent(Component.java:6416)
	at java.desktop/java.awt.Container.processEvent(Container.java:2263)
	at java.desktop/java.awt.Component.dispatchEventImpl(Component.java:5026)
	at java.desktop/java.awt.Container.dispatchEventImpl(Container.java:2321)
	at java.desktop/java.awt.Component.dispatchEvent(Component.java:4858)
	at java.desktop/java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4918)
	at java.desktop/java.awt.LightweightDispatcher.processMouseEvent(Container.java:4547)
	at java.desktop/java.awt.LightweightDispatcher.dispatchEvent(Container.java:4488)
	at java.desktop/java.awt.Container.dispatchEventImpl(Container.java:2307)
	at java.desktop/java.awt.Window.dispatchEventImpl(Window.java:2773)
	at java.desktop/java.awt.Component.dispatchEvent(Component.java:4858)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:778)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:727)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:721)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:95)
	at java.desktop/java.awt.EventQueue$5.run(EventQueue.java:751)
	at java.desktop/java.awt.EventQueue$5.run(EventQueue.java:749)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:748)
	at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.java:908)
	at com.intellij.ide.IdeEventQueue.dispatchMouseEvent(IdeEventQueue.java:846)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:778)
	at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$8(IdeEventQueue.java:424)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computePrioritized(CoreProgressManager.java:698)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:423)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)

[idea.log](https://github.com/setial/intellij-javadocs/files/4388884/idea.log)

**Comment by TSergey** [comment]
To help investigate the issue, could you please describe steps you were done when this error happend?
And please mention whether it was during some other process like project build, importing, or some other parallel process in IDE.

**Comment by manivelpvn** [comment]
This issue occurred when specifically i tried create javadoc for the entire module.
No other process were running in the IDE.

Thanks,Manivel


Sent from Yahoo Mail for iPhone


On Thursday, April 16, 2020, 7:21 PM, Sergey Timofiychuk <notifications@github.com> wrote:




To help investigate the issue, could you please describe steps you were done when this error happend?
And please mention whether it was during some other process like project build, importing, or some other parallel process in IDE.

**Comment by TSergey** [comment]
Fixed since v 4.1.0
